apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
  labels:
    app: {{ .Chart.Name }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ .Values.imagePullSecretConfig |toJson | b64enc | quote }}